version: "3.8"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.68.1
    restart: always
    networks:
      - nexus
    volumes:
      - "/u01/nexus/data:/nexus-data"
    ports:
      - "8081:8081"
      - "8443:8443"

networks:
  nexus:
