apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, get, *, allow
    p, role:admin, repositories, get, *, allow
    p, role:admin, repositories, create, *, allow
    p, role:admin, repositories, update, *, allow
    p, role:admin, repositories, delete, *, allow
    p, role:admin, logs, get, *, allow
    p, role:admin, exec, create, */*, allow
    p, role:devops, applications, get, */*, allow
    p, role:devops, applications, create, */*, allow
    p, role:devops, applications, delete, *, allow
    p, role:devops, applications, get, */*, allow
    p, role:devops, applications, sync, */*, allow
    g, alp, role:admin    