apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  namespace: redis
spec:
  ingressClassName: nginx
  rules:
  - host: redis.prod.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: redis
            port:
              number: 6379
